#Obtainment Method
OM = ["Crafted", "Mob Drop", "Purchased", "Found", "Fished", "Dev Set"]

#Boss Requirement
BR = ["Null", "King Slime", "Eye of Cthulhu", "Brain of Cthulhu", "Eater of Worlds", "Queen Bee", "Skeletron",
      "DeerClops", "Wall of Flesh", "Queen Slime", "Any Mech Boss", "Twins", "Destroyer", "SkelePrime",
      "All Mech Bosses", "Mechdusa", "Plantera", "Golem", "Duke Fishron", "Empress of Light", "Lunatic Cultist",
      "Moon Lord"]

#Main Classes
MC = ["TrueMelee", "Mage", "Ranger", "Summoner", "ProjectileMelee", "Consumable"]

#SubClasses
SC = ["Null", "Summons", "Sentry/Placed Weapon", "Spear", "Boomerang", "Yoyo", "Flail", "Tome", "Wand",
      "Magic Gun", "Bow", "Firearm", "Throwing", "Rocket Launcher", "Shortsword", "Whip"]

#Extended Subclasses
EC = ["Null", "Plant", "Ice", "Fire", "Water", "Hallow", "Event", "Creature", "Crimson", "Corruption"]

#Color
C = ["Null", "Red", "Blue", "Green", "Orange", "Yellow", "Purple"]

#Usability Tier List
U = ["0", "1", "2", "3", "4", "5", "6"]

#Obtainability Tier LIst
O = ["0", "1", "2", "3", "4", "5", "6", "Calender", "NPC Drop"]

#All Weapons and data
W = [
["Copper Shortsword",           OM[0], BR[0], MC[0], SC[14], EC[0], C[0], U[0], O[6], "HoldForFuture"],
["Tin Shortsword",              OM[0], BR[0], MC[0], SC[14], EC[0], C[0], U[0], O[5], "HoldForFuture"],
["Wooden Sword",                OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Boreal Wood Sword",           OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Copper Broadsword",           OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[5], "HoldForFuture"],
["Iron Shortsword",             OM[0], BR[0], MC[0], SC[14], EC[0], C[0], U[0], O[6], "HoldForFuture"],
["Palm Wood Sword",             OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Rich Mahogany Sword",         OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Cactus Sword",                OM[0], BR[0], MC[0], SC[0], EC[1], C[0], U[3], O[6], "HoldForFuture"],
["Lead Shortsword",             OM[0], BR[0], MC[0], SC[14], EC[0], C[0], U[0], O[6], "HoldForFuture"],
["Silver Shortsword",           OM[0], BR[0], MC[0], SC[14], EC[0], C[0], U[0], O[5], "HoldForFuture"],
["Tin Broadsword",              OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[5], "HoldForFuture"],
["Ebonwood Sword",              OM[0], BR[0], MC[0], SC[0], EC[9], C[0], U[3], O[5], "HoldForFuture"],
["Iron Broadsword",             OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Shadewood Sword",             OM[0], BR[0], MC[0], SC[0], EC[8], C[0], U[3], O[5], "HoldForFuture"],
["Tungsten Shortsword",         OM[0], BR[0], MC[0], SC[14], EC[0], C[0], U[0], O[5], "HoldForFuture"],
["Gold Shortsword",             OM[0], BR[0], MC[0], SC[14], EC[0], C[0], U[0], O[5], "HoldForFuture"],
["Lead Shortsword",             OM[0], BR[0], MC[0], SC[14], EC[0], C[0], U[0], O[6], "HoldForFuture"],
["Silver Broadsword",           OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Bladed Glove",                OM[1], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[7], "HoldForFuture"],
["Tungsten Broadsword",         OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Zombie Arm",                  OM[1], BR[0], MC[0], SC[0], EC[7], C[0], U[3], O[2], "HoldForFuture"],
["Ash Wood Sword",              OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[3], O[3], "HoldForFuture"],
["Gold Broadsword",             OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Flymeal",                     OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[2], "HoldForFuture"],
["Platinum Shortsword",         OM[0], BR[0], MC[0], SC[14], EC[0], C[0], U[0], O[4], "HoldForFuture"],
["Mandible Blade",              OM[1], BR[0], MC[0], SC[0], EC[7], C[0], U[3], O[2], "HoldForFuture"],
["Stylish Scissors",            OM[1], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[8], "HoldForFuture"],
["Ruler",                       OM[2], BR[0], MC[0], SC[0], EC[0], C[0], U[0], O[6], "HoldForFuture"],
["Platinum Broadsword",         OM[0], BR[0], MC[0], SC[0], EC[0], C[0], U[3], O[4], "HoldForFuture"],
["Umbrella",                    OM[3], BR[0], MC[0], SC[0], EC[0], C[0], U[3], O[4], "HoldForFuture"],
["Breathing Rod",               OM[3], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[3], "HoldForFuture"],
["Gladius",                     OM[1], BR[0], MC[0], SC[0], EC[0], C[0], U[0], O[2], "HoldForFuture"],
["Bone Sword",                  OM[1], BR[0], MC[0], SC[0], EC[7], C[0], U[3], O[2], "HoldForFuture"],
["Bat Bat",                     OM[1], BR[0], MC[0], SC[0], EC[7], C[0], U[2], O[3], "HoldForFuture"],
["Tentacle Spike",              OM[1], BR[0], MC[0], SC[0], EC[5], C[0], U[4], O[2], "HoldForFuture"],
["Candy Cane Sword",            OM[1], BR[0], MC[0], SC[0], EC[0], C[0], U[4], O[7], "HoldForFuture"],
["Katana",                      OM[2], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[1], "HoldForFuture"],
["Ice Blade",                   OM[3], BR[0], MC[4], SC[0], EC[2], C[0], U[5], O[4], "HoldForFuture"],
["Light's Bane",                OM[0], BR[0], MC[0], SC[0], EC[9], C[0], U[3], O[5], "HoldForFuture"],
["Tragic Umbrella",             OM[2], BR[0], MC[0], SC[0], EC[0], C[0], U[3], O[6], "HoldForFuture"],
["Muramasa",                    OM[3], BR[6], MC[0], SC[0], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Exotic Scimitar",             OM[1], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[8], "HoldForFuture"],
["Phaseblade",                  OM[0], f"{BR[3]} {BR[4]}", MC[0], SC[0], EC[0], C[0], U[1], O[4], "HoldForFuture"],
["Blood Butcherer",             OM[0], BR[0], MC[0], SC[0], EC[8], C[0], U[4], O[5], "HoldForFuture"],
["Starfury",                    OM[3], BR[0], MC[4], SC[0], EC[0], C[0], U[5], O[5], "HoldForFuture"],
["Enchanted Sword",             OM[3], BR[0], MC[4], SC[0], EC[0], C[0], U[5], O[0], "HoldForFuture"],
["Purple Clubberfish",          OM[4], BR[0], MC[0], SC[0], f"{EC[9]} {EC[7]}", C[0], U[2], O[4], "HoldForFuture"],
["Bee Keeper",                  OM[1], BR[5], MC[0], SC[0], EC[0], C[0], U[5], O[4], "HoldForFuture"],
["Falcon Blade",                OM[4], BR[0], MC[0], SC[0], EC[0], C[0], U[2], O[2], "HoldForFuture"],
["Blade of Grass",              OM[0], BR[0], MC[4], SC[0], EC[1], C[0], U[5], O[2], "HoldForFuture"],
["Volcano",                     OM[0], f"{BR[3]} {BR[4]}", MC[0], SC[0], EC[3], C[0], U[5], O[5], "HoldForFuture"],
["Night's Edge",                OM[0], BR[6], MC[0], SC[0], f"{EC[9]} {EC[8]}", C[0], U[6], O[5], "HoldForFuture"],
["Pearlwood Sword",             OM[0], BR[8], MC[0], SC[0], EC[5], C[0], U[0], O[6], "HoldForFuture"],
["Classy Cane",                 OM[1], BR[8], MC[0], SC[0], EC[0], C[0], U[0], O[8], "HoldForFuture"],
["Slap Hand",                   OM[2], BR[8], MC[0], SC[0], EC[0], C[0], U[1], O[3], "HoldForFuture"],
["Cobalt Sword",                OM[0], BR[8], MC[0], SC[0], EC[0], C[0], U[1], O[6], "HoldForFuture"],
["Palladium Sword",             OM[0], BR[8], MC[0], SC[0], EC[0], C[0], U[1], O[6], "HoldForFuture"],
["Phasesaber",                  OM[0], BR[8], MC[0], SC[0], EC[0], C[0], U[2], O[5], "HoldForFuture"],
["Ice Sickle",                  OM[1], BR[8], MC[4], SC[0], EC[2], C[0], U[4], O[3], "HoldForFuture"],
["Brand of the Inferno",        OM[1], BR[10], MC[0], SC[0], EC[0], C[0], U[1], O[3], "HoldForFuture"],
["Mythril Sword",               OM[0], BR[8], MC[0], SC[0], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Orichalcum Sword",            OM[0], BR[8], MC[0], SC[0], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Breaker Blade",               OM[1], BR[8], MC[0], SC[0], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Cutlass",                     OM[1], BR[8], MC[0], SC[0], EC[6], C[0], U[2], O[4], "HoldForFuture"],
["Frostbrand",                  OM[1], BR[8], MC[4], SC[0], EC[2], C[0], U[4], O[4], "HoldForFuture"],
["Adamantite Sword",            OM[0], BR[8], MC[0], SC[0], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Beam Sword",                  OM[1], BR[8], MC[4], SC[0], EC[0], C[0], U[4], O[3], "HoldForFuture"],
["Titanium Sword",              OM[0], BR[8], MC[0], SC[0], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Fetid Baghnakhs",             OM[1], BR[8], MC[0], SC[0], EC[8], C[0], U[3], O[6], "HoldForFuture"],
["Bladetongue",                 OM[4], BR[8], MC[4], SC[0], f"{EC[8]} {EC[7]}", C[0], U[5], O[4], "HoldForFuture"],
["Ham Bat",                     OM[1], BR[8], MC[0], SC[0], f"{EC[2]} {EC[7]}", C[0], U[1], O[4], "HoldForFuture"],
["Excalibur",                   OM[0], BR[10], MC[0], SC[0], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["Waffle's Iron",               OM[1], BR[15], MC[4], SC[0], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["True Excalibur",              OM[0], BR[14], MC[0], SC[0], EC[0], C[0], U[6], O[6], "HoldForFuture"],
["Chlorophyte Saber",           OM[0], BR[14], MC[0], SC[0], EC[1], C[0], U[4], O[6], "HoldForFuture"],
["Death Sickle",                OM[1], BR[14], MC[4], SC[0], EC[6], C[0], U[6], O[5], "HoldForFuture"],
["Psycho Knife",                OM[1], BR[16], MC[0], SC[0], EC[6], C[0], U[0], O[5], "HoldForFuture"],
["Keybrand",                    OM[1], BR[16], MC[0], SC[0], EC[0], C[0], U[2], O[5], "HoldForFuture"],
["Chlorophyte Claymore",        OM[0], BR[14], MC[4], SC[0], EC[1], C[0], U[4], O[6], "HoldForFuture"],
["The Horseman's Blade",        OM[1], BR[16], MC[0], SC[0], EC[6], C[0], U[5], O[3], "HoldForFuture"],
["Christmas Tree Sword",        OM[1], BR[16], MC[4], SC[0], EC[6], C[0], U[4], O[3], "HoldForFuture"],
["True Night's Edge",           OM[0], BR[14], MC[4], SC[0], f"{EC[5]} {EC[8]}", C[0], U[5], O[6], "HoldForFuture"],
["Seedler",                     OM[1], BR[16], MC[4], SC[0], EC[1], C[0], U[5], O[5], "HoldForFuture"],
["Flying Dragon",               OM[1], BR[17], MC[4], SC[0], EC[6], C[0], U[6], O[4], "HoldForFuture"],
["Terra Blade",                 OM[0], BR[16], MC[4], SC[0], EC[6], C[0], U[6], O[6], "HoldForFuture"],
["Influx Waver",                OM[1], BR[17], MC[4], SC[0], EC[6], C[0], U[5], O[5], "HoldForFuture"],
["Star Wraith",                 OM[1], BR[21], MC[4], SC[0], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Meowmere",                    OM[1], BR[21], MC[4], SC[0], EC[7], C[0], U[5], O[5], "HoldForFuture"],
["Wooden Yoyo",                 OM[0], BR[0], MC[0], SC[5], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Rally",                       OM[1], BR[0], MC[0], SC[5], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Malaise",                     OM[0], BR[0], MC[0], SC[5], EC[9], C[0], U[4], O[6], "HoldForFuture"],
["Artery",                      OM[0], BR[0], MC[0], SC[5], EC[8], C[0], U[4], O[6], "HoldForFuture"],
["Amazon",                      OM[0], BR[0], MC[0], SC[5], EC[1], C[0], U[5], O[3], "HoldForFuture"],
["Code 1",                      OM[2], BR[2], MC[0], SC[5], EC[0], C[0], U[3], O[1], "HoldForFuture"],
["Valor",                       OM[3], BR[6], MC[0], SC[5], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Cascade",                     OM[1], BR[6], MC[0], SC[5], EC[3], C[0], U[4], O[3], "HoldForFuture"],
["Hive-Five",                   OM[0], BR[5], MC[0], SC[5], EC[0], C[0], U[5], O[6], "HoldForFuture"],
["Format:C",                    OM[2], BR[8], MC[0], SC[5], EC[0], C[0], U[2], O[3], "HoldForFuture"],
["Gradient",                    OM[2], BR[8], MC[0], SC[5], EC[0], C[0], U[2], O[4], "HoldForFuture"],
["Chik",                        OM[0], BR[8], MC[0], SC[5], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Hel-Fire",                    OM[1], BR[10], MC[0], SC[5], EC[3], C[0], U[3], O[5], "HoldForFuture"],
["Amarok",                      OM[1], BR[8], MC[0], SC[5], EC[2], C[0], U[4], O[5], "HoldForFuture"],
["Code 2",                      OM[2], BR[10], MC[0], SC[5], EC[0], C[0], U[2], O[1], "HoldForFuture"],
["Yelets",                      OM[1], BR[10], MC[0], SC[5], EC[1], C[0], U[4], O[6], "HoldForFuture"],
["Red's Throw",                 OM[5], BR[8], MC[0], SC[5], EC[0], C[0], U[4], O[0], "HoldForFuture"],
["Valkyrie Yoyo",               OM[5], BR[8], MC[0], SC[5], EC[0], C[0], U[4], O[0], "HoldForFuture"],
["Kraken",                      OM[1], BR[16], MC[0], SC[5], EC[4], C[0], U[5], O[5], "HoldForFuture"],
["The Eye of Cthulhu",          OM[1], BR[16], MC[0], SC[5], EC[7], C[0], U[6], O[5], "HoldForFuture"],
["Terrarian",                   OM[1], BR[21], MC[4], SC[5], EC[0], C[0], U[5], O[5], "HoldForFuture"],
["Spear",                       OM[3], BR[0], MC[0], SC[3], EC[0], C[0], U[2], O[5], "HoldForFuture"],
["Trident",                     OM[3], BR[0], MC[0], SC[3], EC[0], C[0], U[2], O[4], "HoldForFuture"],
["Storm Spear",                 OM[3], BR[0], MC[0], SC[3], EC[0], C[0], U[4], O[3], "HoldForFuture"],
["The Rotted Fork",             OM[3], BR[0], MC[0], SC[3], EC[8], C[0], U[4], O[5], "HoldForFuture"],
["Swordfish",                   OM[4], BR[0], MC[0], SC[3], f"{EC[4]} {EC[7]}", C[0], U[2], O[3], "HoldForFuture"],
["Dark Lance",                  OM[3], BR[6], MC[0], SC[3], EC[0], C[0], U[5], O[4], "HoldForFuture"],
["Cobalt Naginata",             OM[0], BR[8], MC[0], SC[3], EC[0], C[0], U[1], O[6], "HoldForFuture"],
["Palladium Pike",              OM[0], BR[8], MC[0], SC[3], EC[0], C[0], U[1], O[6], "HoldForFuture"],
["Mythril Halberd",             OM[0], BR[8], MC[0], SC[3], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Orichalcum Halberd",          OM[0], BR[8], MC[0], SC[3], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Adamantite Glaive",           OM[0], BR[8], MC[0], SC[3], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Titanium Trident",            OM[0], BR[8], MC[0], SC[3], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Gungnir",                     OM[0], BR[10], MC[0], SC[3], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["Ghastly Glaive",              OM[1], BR[10], MC[0], SC[3], EC[6], C[0], U[5], O[5], "HoldForFuture"],
["Chlorophyte Partisan",        OM[0], BR[14], MC[0], SC[3], EC[2], C[0], U[2], O[6], "HoldForFuture"],
["Mushroom Spear",              OM[2], BR[10], MC[0], SC[3], EC[2], C[0], U[4], O[6], "HoldForFuture"],
["Obsidian Swordfish",          OM[4], BR[8], MC[0], SC[3], EC[0], C[0], U[4], O[2], "HoldForFuture"],
["North Pole",                  OM[1], BR[16], MC[4], SC[3], f"{EC[3]} {EC[6]}, {EC[7]}", C[0], U[6], O[3], "HoldForFuture"],
["Wooden Boomerang",            OM[1], BR[0], MC[4], SC[4], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Enchanted Boomerang",         OM[0], BR[0], MC[4], SC[4], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Fruitcake Chakram",           OM[1], BR[0], MC[4], SC[4], EC[0], C[0], U[4], O[7], "HoldForFuture"],
["Bloody Machete",              OM[1], BR[0], MC[4], SC[4], EC[0], C[0], U[3], O[7], "HoldForFuture"],
["Shroomerang",                 OM[1], BR[0], MC[4], SC[4], EC[2], C[0], U[3], O[4], "HoldForFuture"],
["Ice Boomerang",               OM[3], BR[0], MC[4], SC[4], EC[3], C[0], U[5], O[5], "HoldForFuture"],
["Thorn Chakram",               OM[0], BR[0], MC[4], SC[4], EC[1], C[0], U[5], O[3], "HoldForFuture"],
["Combat Wrench",               OM[1], BR[6], MC[4], SC[4], EC[0], C[0], U[1], O[8], "HoldForFuture"],
["Flamarang",                   OM[0], f"{BR[3]} {BR[4]}", MC[4], SC[4], EC[3], C[0], U[3], O[5], "HoldForFuture"],
["Trimarang",                   OM[0], BR[0], MC[4], SC[4], EC[0], C[0], U[6], O[4], "HoldForFuture"],
["Flying Knife",                OM[1], BR[9], MC[4], SC[4], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["Sergeant United Shield",      OM[2], BR[8], MC[4], SC[4], EC[0], C[0], U[2], O[1], "HoldForFuture"],
["Light Disk",                  OM[0], BR[12], MC[4], SC[4], EC[0], C[0], U[3], O[6], "HoldForFuture"],
["Bananarang",                  OM[1], BR[8], MC[4], SC[4], EC[2], C[0], U[6], O[6], "HoldForFuture"],
["Possessed Hatchet",           OM[1], BR[17], MC[4], SC[4], EC[0], C[0], U[6], O[5], "HoldForFuture"],
["Paladin's Hammer",            OM[1], BR[16], MC[4], SC[4], EC[0], C[0], U[3], O[3], "HoldForFuture"],
["Mace",                        OM[1], BR[0], MC[0], SC[6], EC[0], C[0], U[3], O[6], "HoldForFuture"],
["Flaming Mace",                OM[0], BR[0], MC[0], SC[6], EC[3], C[0], U[4], O[6], "HoldForFuture"],
["Ball O' Hurt",                OM[1], BR[0], MC[0], SC[6], EC[9], C[0], U[4], O[5], "HoldForFuture"],
["The Meatball",                OM[0], BR[3], MC[0], SC[6], EC[8], C[0], U[4], O[6], "HoldForFuture"],
["Blue Moon",                   OM[1], BR[6], MC[0], SC[6], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Sunfury",                     OM[1], BR[6], MC[0], SC[6], EC[3], C[0], U[5], O[5], "HoldForFuture"],
["Chain Knife",                 OM[1], BR[8], MC[0], SC[6], EC[0], C[0], U[2], O[3], "HoldForFuture"],
["Drippler Crippler",           OM[1], BR[8], MC[4], SC[6], EC[6], C[0], U[6], O[5], "HoldForFuture"],
["Dao of Pow",                  OM[0], BR[8], MC[0], SC[6], EC[0], C[0], U[4], O[4], "HoldForFuture"],
["Flower Pow",                  OM[1], BR[16], MC[4], SC[6], EC[1], C[0], U[3], O[5], "HoldForFuture"],
["Anchor",                      OM[1], BR[8], MC[0], SC[6], EC[0], C[0], U[0], O[2], "HoldForFuture"],
["Chain Dullotines",            OM[1], BR[8], MC[0], SC[6], EC[9], C[0], U[2], O[4], "HoldForFuture"],
["KO Cannon",                   OM[1], BR[8], MC[0], SC[6], EC[6], C[0], U[2], O[5], "HoldForFuture"],
["Golem Fist",                  OM[1], BR[17], MC[0], SC[6], EC[0], C[0], U[1], O[5], "HoldForFuture"],
["Flairon",                     OM[1], BR[18], MC[4], SC[6], f"{EC[4]} {EC[7]}", C[0], U[5], O[5], "HoldForFuture"],
["Terragrim",                   OM[1], BR[0], MC[0], SC[0], EC[0], C[0], U[4], O[0], "HoldForFuture"],
["Arkhalis",                    OM[5], BR[8], MC[0], SC[0], EC[0], C[0], U[2], O[0], "HoldForFuture"],
["Jousting Lance",              OM[2], BR[0], MC[0], SC[0], EC[0], C[0], U[0], O[2], "HoldForFuture"],
["Shadowflame Knife",           OM[1], BR[8], MC[4], SC[12], f"{EC[3]} {EC[6]}", C[0], U[5], O[5], "HoldForFuture"],
["Hallowed Jousting Lance",     OM[1], BR[10], MC[0], SC[0], EC[0], C[0], U[0], O[6], "HoldForFuture"],
["Sleepy Octopod",              OM[1], BR[8], MC[0], SC[0], EC[6], C[0], U[1], O[3], "HoldForFuture"],
["Scourge of the Corrupter",    OM[3], BR[16], MC[4], SC[12], f"{EC[9]} {EC[7]}", C[0], U[6], O[4], "HoldForFuture"],
["Vampire Knives",              OM[3], BR[16], MC[4], SC[12], EC[8], C[0], U[6], O[4], "HoldForFuture"],
["Shadow Jousting Lance",       OM[1], BR[16], MC[0], SC[0], EC[0], C[0], U[0], O[3], "HoldForFuture"],
["Starlight",                   OM[1], BR[19], MC[0], SC[0], EC[0], C[0], U[5], O[5], "HoldForFuture"],
["Sky Dragon's Fury",           OM[1], BR[17], MC[4], SC[0], f"{EC[6]} {EC[7]}", C[0], U[3], O[5], "HoldForFuture"],
["Daybreak",                    OM[0], BR[20], MC[4], SC[12], EC[3], C[0], U[6], O[6], "HoldForFuture"],
["Solar Eruption",              OM[0], BR[20], MC[0], SC[6], EC[3], C[0], U[3], O[6], "HoldForFuture"],
["Zenith",                      OM[0], BR[21], MC[4], SC[4], EC[0], C[0], U[4], O[0], "HoldForFuture"],

["Wooden Bow",                  OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["Boreal Wood Bow",             OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["Copper Bow",                  OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Palm Wood Bow",               OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["Rich Mahogany Bow",           OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["Tin Bow",                     OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Ebonwood Bow",                OM[0], BR[0], MC[2], SC[10], EC[9], C[0], U[4], O[5], "HoldForFuture"],
["Iron Bow",                    OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Shadewood Bow",               OM[0], BR[0], MC[2], SC[10], EC[8], C[0], U[4], O[5], "HoldForFuture"],
["Lead Bow",                    OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Silver Bow",                  OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Tungsten Bow",                OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Ash Wood Bow",                OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Gold Bow",                    OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[4], "HoldForFuture"],
["Platinum Bow",                OM[0], BR[0], MC[2], SC[10], EC[0], C[0], U[4], O[4], "HoldForFuture"],
["Demon Bow",                   OM[0], BR[0], MC[2], SC[10], EC[9], C[0], U[4], O[5], "HoldForFuture"],
["Tendon Bow",                  OM[0], BR[0], MC[2], SC[10], EC[8], C[0], U[4], O[5], "HoldForFuture"],
["Blood Rain Bow",              OM[1], BR[0], MC[2], SC[10], f"{EC[4]} {EC[6]}", C[0], U[4], O[2], "HoldForFuture"],
["The Bee's Knees",             OM[1], BR[5], MC[2], SC[10], EC[7], C[0], U[5], O[5], "HoldForFuture"],
["Hellwing Bow",                OM[3], BR[6], MC[2], SC[10], EC[3], C[0], U[4], O[4], "HoldForFuture"],
["Molten Fury",                 OM[0], f"{BR[3]} {BR[4]}", MC[2], SC[10], EC[3], C[0], U[5], O[5], "HoldForFuture"],
["Pearlwood Bow",               OM[0], BR[8], MC[2], SC[10], EC[5], C[0], U[0], O[6], "HoldForFuture"],
["Marrow",                      OM[1], BR[8], MC[2], SC[10], EC[0], C[0], U[3], O[2], "HoldForFuture"],
["Ice Bow",                     OM[1], BR[8], MC[2], SC[10], EC[2], C[0], U[4], O[4], "HoldForFuture"],
["Daedalus Stormbow",           OM[1], BR[8], MC[2], SC[10], EC[5], C[0], U[6], O[5], "HoldForFuture"],
["Shadowflame Bow",             OM[1], BR[8], MC[2], SC[10], EC[3], C[0], U[5], O[5], "HoldForFuture"],
["Cobalt Repeater",             OM[0], BR[8], MC[2], SC[10], EC[0], C[0], U[1], O[6], "HoldForFuture"],
["Palladium Repeater",          OM[0], BR[8], MC[2], SC[10], EC[0], C[0], U[1], O[6], "HoldForFuture"],
["Mythril Repeater",            OM[0], BR[8], MC[2], SC[10], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Orichalcum Repeater",         OM[0], BR[8], MC[2], SC[10], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Adamantite Repeater",         OM[0], BR[8], MC[2], SC[10], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Titanium Repeater",           OM[0], BR[8], MC[2], SC[10], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Hallowed Repeater",           OM[0], BR[10], MC[2], SC[10], EC[0], C[0], U[0], O[6], "HoldForFuture"],
["Chlorophyte Repeater",        OM[0], BR[14], MC[2], SC[10], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["Phantom Phoenix",             OM[1], BR[10], MC[2], SC[10], f"{EC[3]} {EC[6]} {EC[7]}", C[0], U[4], O[5], "HoldForFuture"],
["Pulse Bow",                   OM[2], BR[14], MC[2], SC[10], EC[0], C[0], U[5], O[1], "HoldForFuture"],
["Stake Launcher",              OM[1], BR[16], MC[2], SC[0], EC[0], C[0], U[4], O[4], "HoldForFuture"],
["Aerial Bane",                 OM[1], BR[17], MC[2], SC[10], f"{EC[6]} {EC[7]}", C[0], U[4], O[5], "HoldForFuture"],
["Tsunami",                     OM[1], BR[18], MC[2], SC[10], f"{EC[4]} {EC[7]}", C[0], U[6], O[5], "HoldForFuture"],
["Eventide",                    OM[1], BR[19], MC[2], SC[10], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Phantasm",                    OM[0], BR[20], MC[2], SC[10], EC[0], C[0], U[5], O[6], "HoldForFuture"],
["Red Ryder",                   OM[2], BR[0], MC[2], SC[11], EC[0], C[0], U[3], O[1], "HoldForFuture"],
["Flintlock Pistol",            OM[2], BR[0], MC[2], SC[11], EC[0], C[0], U[3], O[6], "HoldForFuture"],
["Musket",                      OM[2], BR[0], MC[2], SC[11], EC[9], C[0], U[3], O[6], "HoldForFuture"],
["The Undertaker",              OM[3], BR[0], MC[2], SC[11], EC[8], C[0], U[3], O[6], "HoldForFuture"],
["Revolver",                    OM[3], BR[0], MC[2], SC[11], EC[0], C[0], U[3], O[1], "HoldForFuture"],
["Minishark",                   OM[2], BR[0], MC[2], SC[11], EC[7], C[0], U[5], O[6], "HoldForFuture"],
["Boomstick",                   OM[3], BR[0], MC[2], SC[11], EC[0], C[0], U[3], O[4], "HoldForFuture"],
["Quad-Barrel Shotgun",         OM[2], BR[6], MC[2], SC[11], EC[0], C[0], U[3], O[6], "HoldForFuture"],
["Handgun",                     OM[3], BR[6], MC[2], SC[11], EC[0], C[0], U[2], O[5], "HoldForFuture"],
["Phoenix Blaster",             OM[0], BR[6], MC[2], SC[11], EC[3], C[0], U[4], O[5], "HoldForFuture"],
["Pew-Matic Horn",              OM[1], BR[7], MC[2], SC[11], EC[2], C[0], U[3], O[5], "HoldForFuture"],
["Clockwork Assault Rifle",     OM[1], BR[8], MC[2], SC[11], EC[0], C[0], U[2], O[5], "HoldForFuture"],
["Gatligator",                  OM[2], BR[8], MC[2], SC[11], EC[0], C[0], U[2], O[1], "HoldForFuture"],
["Shotgun",                     OM[1], BR[8], MC[4], SC[11], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Onyx Blaster",                OM[0], BR[8], MC[2], SC[11], f"{EC[9]} {EC[8]}", C[0], U[3], O[5], "HoldForFuture"],
["Uzi",                         OM[1], BR[8], MC[2], SC[11], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Megashark",                   OM[0], BR[12], MC[2], SC[11], EC[7], C[0], U[4], O[6], "HoldForFuture"],
["Venus Magnum",                OM[1], BR[16], MC[2], SC[11], EC[1], C[0], U[4], O[5], "HoldForFuture"],
["Tactical Shotgun",            OM[1], BR[16], MC[2], SC[11], EC[0], C[0], U[2], O[3], "HoldForFuture"],
["Sniper Rifle",                OM[1], BR[16], MC[2], SC[11], EC[0], C[0], U[0], O[3], "HoldForFuture"],
["Candy Corn Rifle",            OM[1], BR[16], MC[2], SC[11], EC[6], C[0], U[3], O[3], "HoldForFuture"],
["Chain Gun",                   OM[1], BR[16], MC[2], SC[11], EC[6], C[0], U[3], O[3], "HoldForFuture"],
["Xenopopper",                  OM[1], BR[17], MC[2], SC[11], EC[6], C[0], U[2], O[4], "HoldForFuture"],
["Vortex Beater",               OM[0], BR[20], MC[2], SC[11], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["S.D.M.G.",                    OM[1], BR[21], MC[2], SC[11], EC[7], C[0], U[5], O[5], "HoldForFuture"],
["Grenade Launcher",            OM[1], BR[16], MC[2], SC[13], EC[0], C[0], U[1], O[5], "HoldForFuture"],
["Proximity Mine Launcher",     OM[2], BR[16], MC[2], SC[13], EC[0], C[0], U[1], O[6], "HoldForFuture"],
["Rocket Launcher",             OM[1], BR[16], MC[2], SC[13], EC[0], C[0], U[1], O[4], "HoldForFuture"],
["Nail Gun",                    OM[1], BR[16], MC[2], SC[0], EC[6], C[0], U[1], O[4], "HoldForFuture"],
["Stynger",                     OM[1], BR[17], MC[2], SC[0], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Jack 'O Lantern Launcher",    OM[1], BR[16], MC[2], SC[13], EC[6], C[0], U[2], O[4], "HoldForFuture"],
["Snowman Cannon",              OM[1], BR[16], MC[2], SC[13], EC[6], C[0], U[2], O[4], "HoldForFuture"],
["Celebration",                 OM[2], BR[17], MC[2], SC[13], EC[0], C[0], U[3], O[4], "HoldForFuture"],
["Electrosphere Launcher",      OM[1], BR[17], MC[2], SC[13], EC[6], C[0], U[2], O[4], "HoldForFuture"],
["Celebration Mk2",             OM[1], BR[21], MC[2], SC[13], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Paper Airplane",              OM[1], BR[0], MC[5], SC[12], EC[0], C[0], U[1], O[5], "HoldForFuture"],
["White Paper Airplane",        OM[1], BR[0], MC[5], SC[12], EC[0], C[0], U[1], O[5], "HoldForFuture"],
["Shuriken",                    f"{OM[2]} {OM[3]}", BR[0], MC[5], SC[12], EC[0], C[0], U[3], O[6], "HoldForFuture"],
["Throwing Knife",              f"{OM[2]} {OM[3]}", BR[0], MC[5], SC[12], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Poisoned Knife",              OM[1], BR[0], MC[5], SC[12], EC[0], C[0], U[5], O[5], "HoldForFuture"],
["Snowball",                    OM[1], BR[0], MC[5], SC[12], EC[2], C[0], U[1], O[6], "HoldForFuture"],
["Spiky Ball",                  f"{OM[1]} {OM[2]}", BR[0], MC[5], SC[12], EC[0], C[0], U[5], O[6], "HoldForFuture"],
["Bone",                        OM[1], BR[0], MC[5], SC[12], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Rotten Egg",                  OM[3], BR[0], MC[5], SC[12], EC[0], C[0], U[2], O[7], "HoldForFuture"],
["Star Anise",                  OM[1], BR[0], MC[5], SC[12], EC[0], C[0], U[2], O[7], "HoldForFuture"],
["Molotov Cocktail",            OM[0], BR[0], MC[5], SC[12], EC[0], C[0], U[6], O[5], "HoldForFuture"],
["Frost Daggerfish",            OM[4], BR[0], MC[5], SC[12], f"{EC[2]} {EC[7]}", C[0], U[5], O[4], "HoldForFuture"],
["Javelin",                     OM[1], BR[0], MC[5], SC[12], EC[0], C[0], U[6], O[6], "HoldForFuture"],
["Bone Javelin",                OM[0], BR[0], MC[5], SC[12], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Bone Throwing Knife",         OM[0], BR[0], MC[5], SC[12], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Grenade",                     f"{OM[2]} {OM[3]}", BR[0], MC[5], SC[12], EC[0], C[0], U[5], O[6], "HoldForFuture"],
["Sticky Grenade",              OM[0], BR[0], MC[5], SC[12], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Bouncy Grenade",              OM[0], BR[0], MC[5], SC[12], EC[0], C[0], U[1], O[5], "HoldForFuture"],
["Beenade",                     f"{OM[0]} {OM[1]}", BR[5], MC[5], SC[12], EC[7], C[0], U[6], O[6], "HoldForFuture"],
["Happy Grenade",               f"{OM[1]} {OM[2]}", BR[0], MC[5], SC[12], EC[0], C[0], U[5], O[6], "HoldForFuture"],
["Blowpipe",                    OM[3], BR[0], MC[2], SC[0], EC[0], C[0], U[3], O[4], "HoldForFuture"],
["Sandgun",                     OM[0], BR[0], MC[2], SC[0], EC[0], C[0], U[6], O[5], "HoldForFuture"],
["Blowgun",                     OM[2], BR[5], MC[2], SC[0], EC[0], C[0], U[3], O[6], "HoldForFuture"],
["Snowball Cannon",             OM[3], BR[0], MC[2], SC[0], EC[2], C[0], U[5], O[4], "HoldForFuture"],
["Paintball Gun",               OM[1], BR[0], MC[2], SC[0], EC[0], C[0], U[5], O[8], "HoldForFuture"],
["Ale Tosser",                  OM[1], f"{BR[3]} {BR[4]}", MC[2], SC[0], EC[0], C[0], U[2], O[8], "HoldForFuture"],
["Harpoon",                     OM[1], BR[0], MC[2], SC[0], EC[0], C[0], U[1], O[4], "HoldForFuture"],
["Star Cannon",                 OM[0], f"{BR[3]} {BR[4]}", MC[2], SC[0], EC[0], C[0], U[6], O[5], "HoldForFuture"],
["Toxicarp",                    OM[4], BR[8], MC[2], SC[0], f"{EC[4]} {EC[9]} {EC[7]}", C[0], U[6], O[4], "HoldForFuture"],
["Dart Pistal",                 OM[1], BR[8], MC[2], SC[0], EC[8], C[0], U[3], O[5], "HoldForFuture"],
["Dart Rifle",                  OM[1], BR[8], MC[2], SC[0], EC[9], C[0], U[3], O[5], "HoldForFuture"],
["Coin Gun",                    OM[1], BR[8], MC[2], SC[0], EC[6], C[0], U[4], O[2], "HoldForFuture"],
["Flamethrower",                OM[0], BR[13], MC[2], SC[0], EC[3], C[0], U[2], O[6], "HoldForFuture"],
["Piranha Gun",                 OM[3], BR[16], MC[2], SC[0], EC[7], C[0], U[5], O[4], "HoldForFuture"],
["Elf Melter",                  OM[1], BR[16], MC[2], SC[0], f"{EC[2]} {EC[3]}", C[0], U[2], O[4], "HoldForFuture"],
["Super Star Shooter",          OM[0], BR[10], MC[2], SC[0], EC[0], C[0], U[6], O[5], "HoldForFuture"],

["Wand of Sparking",            OM[3], BR[0], MC[1], SC[8], EC[3], C[0], U[5], O[5], "HoldForFuture"],
["Wand of Frosting",            OM[0], BR[0], MC[1], SC[8], EC[2], C[0], U[6], O[5], "HoldForFuture"],
["Thunder Zapper",              OM[3], BR[0], MC[1], SC[8], EC[0], C[0], U[4], O[4], "HoldForFuture"],
["Amethyst Staff",              OM[0], BR[0], MC[1], SC[8], EC[0], C[0], U[1], O[6], "HoldForFuture"],
["Topaz Stuff",                 OM[0], BR[0], MC[1], SC[8], EC[0], C[0], U[1], O[6], "HoldForFuture"],
["Sapphire Staff",              OM[0], BR[0], MC[1], SC[8], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Emerald Staff",               OM[0], BR[0], MC[1], SC[8], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Ruby Staff",                  OM[0], BR[0], MC[1], SC[8], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Diamond Staff",               OM[0], BR[0], MC[1], SC[8], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Amber Staff",                 OM[0], BR[0], MC[1], SC[8], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Vilethorn",                   OM[3], BR[0], MC[1], SC[8], EC[9], C[0], U[4], O[4], "HoldForFuture"],
["Weather Pain",                OM[1], BR[7], MC[1], SC[8], EC[2], C[0], U[5], O[5], "HoldForFuture"],
["Magic Missile",               OM[3], BR[6], MC[1], SC[8], EC[4], C[0], U[4], O[4], "HoldForFuture"],
["Aqua Scepter",                OM[3], BR[6], MC[1], SC[8], EC[4], C[0], U[5], O[4], "HoldForFuture"],
["Flower of Fire",              OM[3], BR[6], MC[1], SC[8], EC[3], C[0], U[4], O[4], "HoldForFuture"],
["Flamelash",                   OM[3], BR[6], MC[1], SC[8], EC[3], C[0], U[5], O[4], "HoldForFuture"],
["Sky Fracture",                OM[0], BR[8], MC[1], SC[8], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Crystal Serpent",             OM[4], BR[8], MC[1], SC[8], EC[4], C[0], U[6], O[4], "HoldForFuture"],
["Flower of Frost",             OM[1], BR[8], MC[1], SC[8], EC[2], C[0], U[3], O[4], "HoldForFuture"],
["Frost Staff",                 OM[1], BR[8], MC[1], SC[8], EC[2], C[0], U[5], O[5], "HoldForFuture"],
["Crystal Vile Shard",          OM[1], BR[8], MC[1], SC[8], EC[5], C[0], U[3], O[4], "HoldForFuture"],
["Life Drain",                  OM[1], BR[8], MC[1], SC[8], EC[8], C[0], U[5], O[4], "HoldForFuture"],
["Meteor Staff",                OM[0], BR[8], MC[1], SC[8], EC[0], C[0], U[6], O[6], "HoldForFuture"],
["Poison Staff",                OM[1], BR[8], MC[1], SC[8], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Rainbow Rod",                 OM[0], BR[11], MC[1], SC[8], EC[5], C[0], U[5], O[5], "HoldForFuture"],
["Unholy Trident",              OM[1], BR[10], MC[1], SC[8], EC[0], C[0], U[4], O[2], "HoldForFuture"],
["Tome of Infinite Wisdom",     OM[1], BR[10], MC[1], SC[8], EC[6], C[0], U[4], O[4], "HoldForFuture"],
["Venom Staff",                 OM[0], BR[14], MC[1], SC[8], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Nettle Burst",                OM[1], BR[16], MC[1], SC[8], EC[1], C[0], U[3], O[5], "HoldForFuture"],
["Bat Scepter",                 OM[1], BR[16], MC[1], SC[8], f"{EC[6]} {EC[7]}" , C[0], U[4], O[4], "HoldForFuture"],
["Blizzard Staff",              OM[1], BR[16], MC[1], SC[8], f"{EC[2]} {EC[6]}", C[0], U[5], O[4], "HoldForFuture"],
["Inferno Fork",                OM[1], BR[16], MC[1], SC[8], EC[3], C[0], U[4], O[2], "HoldForFuture"],
["Shadowbeam Staff",            OM[1], BR[16], MC[1], SC[8], EC[0], C[0], U[2], O[3], "HoldForFuture"],
["Spectre Staff",               OM[1], BR[16], MC[1], SC[8], EC[0], C[0], U[5], O[2], "HoldForFuture"],
["Resonance Scepter",           OM[1], BR[16], MC[1], SC[8], EC[0], C[0], U[2], O[8], "HoldForFuture"],
["Razorpine",                   OM[1], BR[16], MC[1], SC[8], f"{EC[1]} {EC[6]}", C[0], U[5], O[4], "HoldForFuture"],
["Staff of Earth",              OM[1], BR[17], MC[1], SC[8], EC[0], C[0], U[0], O[4], "HoldForFuture"],
["Betsy's Wrath",               OM[1], BR[17], MC[1], SC[8], f"{EC[3]} {EC[7]}", C[0], U[2], O[5], "HoldForFuture"],
["Gray Zapinator",              OM[2], BR[0], MC[1], SC[9], EC[0], C[0], U[3], O[1], "HoldForFuture"],
["Space Gun",                   OM[0], f"{BR[3]} {BR[4]}", MC[1], SC[9], EC[0], C[0], U[5], O[6], "HoldForFuture"],
["Bee Gun",                     OM[1], BR[5], MC[1], SC[9], EC[7], C[0], U[4], O[5], "HoldForFuture"],
["Laser Rifle",                 OM[1], BR[8], MC[1], SC[9], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Orange Zapinator",            OM[2], BR[8], MC[1], SC[9], EC[0], C[0], U[3], O[1], "HoldForFuture"],
["Wasp Gun",                    OM[1], BR[16], MC[1], SC[9], EC[7], C[0], U[3], O[5], "HoldForFuture"],
["Leaf BLower",                 OM[1], BR[16], MC[1], SC[9], EC[1], C[0], U[4], O[5], "HoldForFuture"],
["Rainbow Gun",                 OM[3], BR[16], MC[1], SC[9], EC[5], C[0], U[2], O[3], "HoldForFuture"],
["Heat Ray",                    OM[1], BR[17], MC[1], SC[9], EC[0], C[0], U[2], O[5], "HoldForFuture"],
["Laser Machinegun",            OM[1], BR[17], MC[1], SC[9], EC[0], C[0], U[4], O[4], "HoldForFuture"],
["Charged Blaster Cannon",      OM[1], BR[17], MC[1], SC[9], EC[0], C[0], U[2], O[3], "HoldForFuture"],
["Bubble Gun",                  OM[1], BR[18], MC[1], SC[9], EC[4], C[0], U[6], O[4], "HoldForFuture"],
["Water Bolt",                  OM[3], BR[6], MC[1], SC[7], EC[4], C[0], U[5], O[4], "HoldForFuture"],
["Book of Skulls",              OM[1], BR[6], MC[1], SC[7], EC[0], C[0], U[4], O[2], "HoldForFuture"],
["Demon Scythe",                OM[1], BR[0], MC[1], SC[7], EC[0], C[0], U[4], O[4], "HoldForFuture"],
["Cursed Flames",               OM[0], BR[8], MC[1], SC[7], f"{EC[3]} {EC[9]}", C[0], U[3], O[5], "HoldForFuture"],
["Golden Shower",               OM[0], BR[8], MC[1], SC[7], EC[8], C[0], U[5], O[5], "HoldForFuture"],
["Crystal Storm",               OM[0], BR[8], MC[1], SC[7], EC[5], C[0], U[3], O[4], "HoldForFuture"],
["Magnet Sphere",               OM[1], BR[16], MC[1], SC[7], EC[0], C[0], U[1], O[4], "HoldForFuture"],
["Razorblade Typhoon",          OM[1], BR[18], MC[1], SC[7], EC[2], C[0], U[5], O[4], "HoldForFuture"],
["Lunar Flare",                 OM[1], BR[21], MC[1], SC[7], EC[0], C[0], U[6], O[5], "HoldForFuture"],
["Crimson Rod",                 OM[3], BR[0], MC[1], SC[2], EC[8], C[0], U[0], O[4], "HoldForFuture"],
["Ice Rod",                     OM[2], BR[8], MC[1], SC[0], EC[2], C[0], U[0], O[6], "HoldForFuture"],
["Clinger Staff",               OM[1], BR[8], MC[1], SC[2], EC[3], C[0], U[0], O[4], "HoldForFuture"],
["Nimbus Rod",                  OM[1], BR[8], MC[1], SC[2], EC[2], C[0], U[1], O[5], "HoldForFuture"],
["Magic Dagger",                OM[1], BR[8], MC[1], SC[12], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Medusa Head",                 OM[1], BR[8], MC[1], SC[0], EC[7], C[0], U[3], O[2], "HoldForFuture"],
["Spirit Flame",                OM[0], BR[8], MC[1], SC[0], EC[3], C[0], U[6], O[3], "HoldForFuture"],
["Shadowflame Hex Doll",        OM[1], BR[8], MC[1], SC[0], f"{EC[3]} {EC[6]}", C[0], U[2], O[4], "HoldForFuture"],
["Blood Thorn",                 OM[1], BR[8], MC[1], SC[0], f"{EC[6]} {EC[1]}", C[0], U[2], O[4], "HoldForFuture"],
["Magical Harp",                OM[0], BR[11], MC[1], SC[0], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["Toxic Flask",                 OM[1], BR[16], MC[1], SC[0], EC[0], C[0], U[2], O[4], "HoldForFuture"],
["Nightglow",                   OM[1], BR[19], MC[1], SC[0], EC[5], C[0], U[5], O[5], "HoldForFuture"],
["Stellar Tune",                OM[1], BR[19], MC[1], SC[0], EC[5], C[0], U[4], O[5], "HoldForFuture"],
["Nebula Arcanum",              OM[0], BR[20], MC[1], SC[0], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["Nebula Blaze",                OM[0], BR[20], MC[1], SC[0], EC[0], C[0], U[6], O[6], "HoldForFuture"],
["Last Prism",                  OM[1], BR[21], MC[1], SC[0], EC[0], C[0], U[6], O[5], "HoldForFuture"],

["Finch Staff",                 OM[3], BR[0], MC[3], SC[1], EC[7], C[0], U[1], O[5], "HoldForFuture"],
["Slime Staff",                 OM[1], BR[0], MC[3], SC[1], EC[0], C[0], U[1], O[2], "HoldForFuture"],
["Flinx Staff",                 OM[0], BR[0], MC[3], SC[1], EC[2], C[0], U[1], O[5], "HoldForFuture"],
["Abigail's Flower",            OM[3], BR[0], MC[3], SC[1], EC[1], C[0], U[5], O[6], "HoldForFuture"],
["Hornet Staff",                OM[0], BR[5], MC[3], SC[1], EC[1], C[0], U[3], O[6], "HoldForFuture"],
["Vampire Frog Staff",          OM[1], BR[0], MC[3], SC[1], f"{EC[6]} {EC[7]}", C[0], U[4], O[4], "HoldForFuture"],
["Imp Staff",                   OM[0], f"{BR[3]} {BR[4]}", MC[3], SC[1], EC[3], C[0], U[4], O[6], "HoldForFuture"],
["Blade Staff",                 OM[1], BR[9], MC[3], SC[1], EC[0], C[0], U[2], O[5], "HoldForFuture"],
["Spider Staff",                OM[0], BR[8], MC[3], SC[1], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Pirate Staff",                OM[1], BR[8], MC[3], SC[1], EC[6], C[0], U[1], O[2], "HoldForFuture"],
["Sanguine Staff",              OM[1], BR[8], MC[3], SC[1], EC[6], C[0], U[4], O[2], "HoldForFuture"],
["Optic Staff",                 OM[0], BR[11], MC[3], SC[1], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Deadly Sphere Staff",         OM[1], BR[16], MC[3], SC[1], EC[0], C[0], U[5], O[4], "HoldForFuture"],
["Pygmy Staff",                 OM[1], BR[16], MC[3], SC[1], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Raven Staff",                 OM[1], BR[16], MC[3], SC[1], EC[6], C[0], U[4], O[4], "HoldForFuture"],
["Desert Tiger Staff",          OM[3], BR[16], MC[3], SC[1], EC[0], C[0], U[4], O[3], "HoldForFuture"],
["Tempest Staff",               OM[1], BR[18], MC[3], SC[1], EC[0], C[0], U[5], O[5], "HoldForFuture"],
["Terraprisma",                 OM[1], BR[19], MC[3], SC[1], EC[0], C[0], U[4], O[0], "HoldForFuture"],
["Xeno Staff",                  OM[1], BR[17], MC[3], SC[1], EC[6], C[0], U[3], O[4], "HoldForFuture"],
["Stardust Cell Staff",         OM[0], BR[20], MC[3], SC[1], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["Stardust Dragon Staff",       OM[0], BR[20], MC[3], SC[1], EC[0], C[0], U[6], O[6], "HoldForFuture"],
["Houncius Shootius",           OM[1], BR[7], MC[3], SC[2], EC[0], C[0], U[1], O[5], "HoldForFuture"],
["Lightning Aura",              OM[2], f"{BR[3]} {BR[4]}", MC[3], SC[2], EC[6], C[0], U[1], O[6], "HoldForFuture"],
["Flameburst",                  OM[2], f"{BR[3]} {BR[4]}", MC[3], SC[2], EC[6], C[0], U[4], O[6], "HoldForFuture"],
["Explosive Trap",              OM[2], f"{BR[3]} {BR[4]}", MC[3], SC[2], EC[6], C[0], U[2], O[6], "HoldForFuture"],
["Ballista",                    OM[2], f"{BR[3]} {BR[4]}", MC[3], SC[2], EC[6], C[0], U[5], O[6], "HoldForFuture"],
["Queen Spider Staff",          OM[0], BR[8], MC[3], SC[2], EC[0], C[0], U[6], O[6], "HoldForFuture"],
["Staff of the Frost Hydra",    OM[3], BR[16], MC[3], SC[2], EC[0], C[0], U[2], O[3], "HoldForFuture"],
["Lunar Portal Staff",          OM[1], BR[21], MC[3], SC[2], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Rainbow Crystal Staff",       OM[1], BR[21], MC[3], SC[2], EC[0], C[0], U[3], O[5], "HoldForFuture"],
["Leather Whip",                OM[2], BR[0], MC[3], SC[15], EC[0], C[0], U[2], O[6], "HoldForFuture"],
["Snapthorn",                   OM[0], BR[0], MC[3], SC[15], EC[1], C[0], U[4], O[3], "HoldForFuture"],
["Spinal Tap",                  OM[0], BR[6], MC[3], SC[15], EC[0], C[0], U[4], O[5], "HoldForFuture"],
["Firecracker",                 OM[1], BR[8], MC[3], SC[15], EC[3], C[0], U[5], O[5], "HoldForFuture"],
["Cool Whip",                   OM[0], BR[8], MC[3], SC[15], EC[2], C[0], U[6], O[5], "HoldForFuture"],
["Durendal",                    OM[0], BR[10], MC[3], SC[15], EC[0], C[0], U[4], O[6], "HoldForFuture"],
["Dark Harvest",                OM[1], BR[16], MC[3], SC[15], EC[6], C[0], U[5], O[4], "HoldForFuture"],
["Morningstar",                 OM[1], BR[16], MC[3], SC[15], EC[0], C[0], U[5], O[4], "HoldForFuture"],
["Kaleidoscope",                OM[1], BR[19], MC[3], SC[15], EC[0], C[0], U[6], O[5], "HoldForFuture"],

["Snowball Launcher",           OM[1], BR[0], MC[2], SC[2], EC[2], C[0], U[1], O[4], "HoldForFuture"],
["Firework Rockets",            OM[2], BR[8], MC[2], SC[2], EC[3], C[0], U[1], O[6], "HoldForFuture"],
["Cannon",                      OM[2], BR[8], MC[2], SC[2], EC[0], C[0], U[1], O[6], "HoldForFuture"],
["Bunny Cannon",                OM[2], BR[8], MC[2], SC[2], EC[0], C[0], U[1], O[6], "HoldForFuture"],
["Land Mine",                   OM[2], BR[16], MC[2], SC[2], EC[3], C[0], U[2], O[6], "HoldForFuture"],
["Flare Gun",                   OM[3], BR[0], MC[2], SC[2], EC[3], C[0], U[2], O[6], "HoldForFuture"],
    ]

# Seperates weapons into standard progression tiers so that one weapon from every tier makes a playthrough possible
# tiers are as follows, 1 craftable and 1 loot item before any boss can be killed, 1 weapon after beating world evil
# boss, 1 item for queen bee, skeletron, and deerclops, 1 craftable and 1 loot item for early hardmode, 1 weapon for up
# to plantera, 1 weapon for post plantera, 1 weapon between duke and Golem, 1 weapon from solar event, and one empress
# or Moon lord weapon
x = 0
Tiers = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
while x < len(W):
    if SC[1] not in W[x][4] and SC[2] not in W[x][4] and MC[5] not in W[x][3]:
        if W[x][2] in BR[0] and W[x][1] in OM[0] and SC[1] and MC[5] != W[x][3]:
            Tiers[0].append(W[x])

        if BR[0] in W[x][2] and (OM[1] in W[x][1] or OM[2] in W[x][1] or OM[3] in W[x][1] or OM[4] in W[x][1]):
            Tiers[1].append(W[x])

        if BR[1] in W[x][2] or BR[2] in W[x][2] or BR[3] in W[x][2] or BR[4] in W[x][2]:
            Tiers[2].append(W[x])

        if W[x][2] in (BR[5], BR[7]):
            Tiers[3].append(W[x])

        if W[x][2] in BR[6]:
            Tiers[4].append(W[x])

        if W[x][2] in BR[8] and W[x][1] in OM[0]:
            Tiers[5].append(W[x])

        if W[x][2] in BR[8] and W[x][1] in (OM[1], OM[2], OM[3], OM[4]):
            Tiers[6].append(W[x])

        if W[x][2] in (BR[9], BR[10], BR[11], BR[12], BR[13], BR[14]):
            Tiers[7].append(W[x])

        if W[x][2] in BR[16]:
            Tiers[8].append(W[x])

        if W[x][2] in (BR[17], BR[18]):
            Tiers[9].append(W[x])

        if W[x][2] in BR[20]:
            Tiers[10].append(W[x])

        if W[x][2] in (BR[19], BR[21]):
            Tiers[11].append(W[x])

    if SC[1] in W[x][4] and MC[3] in W[x][3]:
        Tiers[12].append(W[x])
        Tiers[13].append(W[x])

    if SC[2] in W[x][4] and MC[3] in W[x][3]:
        if EC[6] in W[x][5]:
            Tiers[15].append(W[x])
        else:
            Tiers[14].append(W[x])

    if MC[5] in W[x][3]:
        Tiers[16].append(W[x])
        Tiers[17].append(W[x])
    x += 1
x = 0
#while x < len(Tiers[1]):
#    print(Tiers[1][x][0])
#    x += 1